/****************************************************************************************
 * Copyright (c) 2023 Deepanshu Pratik <deepanshu.pratik@gmail.com>                     *
 *                                                                                      *
 * This program is free software; you can redistribute it and/or modify it under        *
 * the terms of the Apache License as published by the Free Software                    *
 * Foundation; either version 2 of the License, or (at your option) any later           *
 * version.                                                                             *
 *                                                                                      *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY      *
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A      *
 * PARTICULAR PURPOSE. See the Apache License for more details.                         *
 *                                                                                      *
 * You should have received a copy of the Apache License along with this program.       *
 *  If not, see <http://www.apache.org/licenses/>.                                      *
 ****************************************************************************************/
using Gtk;

namespace linux_onboarding {

    /**
     * The one place that answers "what colour is this app?".
     *
     * It exists for the startup flash (#33). A WebKit.WebView's default base
     * colour is opaque white, so the deck used to open as a white rectangle and
     * repaint into the real page — worst on exactly the builds that look best,
     * because a dark branding makes the white maximally visible. Fixing that
     * means telling the view what colour to be *before* it has a document, which
     * means somewhere has to know the app's background outside CSS.
     *
     * Deliberately a lookup and not a constant. Three sources, in order:
     *
     *  1. `Background=` in branding.conf. A distro that ships a dark theme.css
     *     has to be able to say so: nothing here parses CSS, so the sheet's own
     *     background is invisible to us, and guessing it from the GTK theme gets
     *     a light colour behind a dark page.
     *  2. The GTK theme's own `theme_bg_color`, which is what app.css asks for
     *     when a distro sets no Background. Following the user's theme is the
     *     right default for an unbranded build.
     *  3. A neutral mid-grey, if even that lookup fails. Never white: white is
     *     the failure this class exists to prevent, and a wrong grey is a much
     *     smaller error than a flash.
     *
     * Resolved once. The branding is compiled in and the GTK theme does not
     * change under us within a run.
     *
     * ## The per-desktop palette (#32)
     *
     * The other half of this class: an accent colour that follows the desktop
     * the app is running on, so a Regolith build does not look identical on
     * sway, GNOME and KDE.
     *
     * Sources, in order, and the reasoning is the same each time — prefer what
     * someone actually chose over what we guessed:
     *
     *  1. `Accent=` in branding.conf. A distro that has an opinion outranks
     *     everything; this is the opt-out.
     *  2. The desktop, where it will say. GNOME keeps `accent-color` in
     *     org.gnome.desktop.interface (GNOME 47 and later); KDE keeps
     *     `AccentColor` in kdeglobals. Both are read defensively — the GSettings
     *     key does not exist on older GNOME, and asking for a key a schema does
     *     not have aborts the process.
     *  3. A shipped default per desktop id, so every session has an accent even
     *     when nothing can be read.
     *
     * **The distro's theme.css still wins.** The palette is loaded at
     * PRIORITY_APPLICATION, beneath app.css at PRIORITY_USER and the distro's
     * sheet above that, so it supplies defaults rather than overriding a
     * designed look. A distro that wants none of it sets `Accent=` and gets
     * exactly what it asked for on every desktop.
     *
     * The slides get the same colour through `app:///palette.css`, generated by
     * web_palette_css() and served by SlideScheme. Without that the GTK window
     * and the HTML deck would drift apart at the seam, which is the one place a
     * mismatch is impossible to miss.
     */
    public class Palette : GLib.Object {

        // Not white, on purpose — see the class comment.
        private const string FALLBACK = "#303030";

        private static Gdk.RGBA? cached = null;

        /**
         * The colour to paint where the app's own content has not painted yet.
         *
         * Safe to call before any window is realised: the theme lookup goes
         * through a throwaway widget's style context, which resolves against the
         * default screen's providers and needs no toplevel.
         */
        public static Gdk.RGBA window_background () {
            if (cached != null) return cached;

            var rgba = Gdk.RGBA ();

            var declared = Branding.get_default ().background;
            if (declared != "" && rgba.parse (declared)) {
                cached = rgba;
                return cached;
            }
            if (declared != "") {
                warning ("branding.conf: Background=%s is not a colour GDK understands; " +
                         "falling back to the GTK theme", declared);
            }

            // A Label rather than a Window: constructing a Gtk.Window here would
            // put a second toplevel in the application's window list.
            var probe = new Gtk.Label ("");
            if (probe.get_style_context ().lookup_color ("theme_bg_color", out rgba)) {
                cached = rgba;
                return cached;
            }

            rgba.parse (FALLBACK);
            cached = rgba;
            return cached;
        }

        /* ---------------------------------------------------------------- *
         *  The per-desktop palette                                          *
         * ---------------------------------------------------------------- */

        private const string DEFAULT_ACCENT = "#4a90d9";

        private static string? cached_accent = null;

        /**
         * The accent this session should use — a distro's choice, else the
         * desktop's own, else the shipped default for that desktop.
         */
        public static string accent_hex () {
            if (cached_accent != null) return cached_accent;

            var declared = Branding.get_default ().accent;
            if (declared != "") {
                if (is_hex_colour (declared)) {
                    cached_accent = declared;
                    return cached_accent;
                }
                warning ("branding.conf: Accent=%s is not a #rrggbb colour; " +
                         "following the desktop instead", declared);
            }

            var desktop = Desktop.get_default ().primary;
            cached_accent = desktop_accent (desktop) ?? default_accent_for (desktop);
            return cached_accent;
        }

        /** Whether the deck should be dark: the distro's say, else the desktop's. */
        public static bool prefer_dark () {
            switch (Branding.get_default ().color_scheme.down ()) {
                case "dark":  return true;
                case "light": return false;
                default:      break;   // "desktop", and anything unrecognised
            }
            return desktop_prefers_dark ();
        }

        /**
         * Publish the palette to GTK, and follow the desktop into dark mode.
         *
         * PRIORITY_APPLICATION deliberately: app.css (PRIORITY_USER) and the
         * distro's theme.css (USER + 1) both sit above this, so these are
         * defaults that a designed sheet overrides rather than the other way
         * round. Named colours resolve across providers regardless of which one
         * defined them, which is how app.css can use @onboarding_accent while
         * this provider is the one that knows its value.
         */
        public static void apply (Gdk.Screen screen) {
            var provider = new Gtk.CssProvider ();
            try {
                provider.load_from_data (gtk_css_for (accent_hex ()));
            } catch (Error e) {
                // Generated from a validated colour, so this is a bug in the
                // template rather than in anyone's configuration.
                warning ("palette: generated CSS did not parse: %s", e.message);
                return;
            }
            Gtk.StyleContext.add_provider_for_screen (
                screen, provider, Gtk.STYLE_PROVIDER_PRIORITY_APPLICATION);

            var settings = Gtk.Settings.get_for_screen (screen);
            if (settings != null) settings.gtk_application_prefer_dark_theme = prefer_dark ();
        }

        /** The stylesheet SlideScheme serves at app:///palette.css. */
        public static string web_palette_css () {
            return web_css_for (accent_hex (), prefer_dark ());
        }

        // ---- generated stylesheets (pure; covered by tests/test_palette) ----

        /**
         * The names app.css and flow.css consume. Kept small on purpose: every
         * name defined here is one a distro may have to reason about, and the
         * accent is the only thing that genuinely varies by desktop.
         */
        internal static string gtk_css_for (string accent) {
            return ("@define-color onboarding_accent %s;\n" +
                    "@define-color onboarding_accent_fg #ffffff;\n" +
                    "@define-color onboarding_accent_dim alpha(%s, 0.14);\n").printf (accent, accent);
        }

        /**
         * The same colour for the HTML deck. Custom properties rather than rules,
         * so a page uses them where it wants them; `color-scheme` is here because
         * it is what makes a form control or a scrollbar in a slide match the
         * rest of the app.
         *
         * Served as a user-linked sheet, so a page that sets its own :root wins —
         * a distro's design is not overridden by the desktop it happens to run on.
         */
        internal static string web_css_for (string accent, bool dark) {
            return (":root {\n" +
                    "  --desktop-accent: %s;\n" +
                    "  color-scheme: %s;\n" +
                    "}\n").printf (accent, dark ? "dark" : "light");
        }

        // ---- reading the desktop (guarded; the pure halves are testable) ----

        /**
         * Asked of the desktop that is actually running, not of both.
         *
         * kdeglobals exists on plenty of machines that are not running Plasma —
         * one KDE application is enough to create it — so reading it anywhere
         * else would dress a GNOME session in the accent of a file nobody meant
         * as a system setting.
         */
        private static string? desktop_accent (string desktop) {
            if (is_kde (desktop)) {
                var kde = read_kdeglobals ();
                return kde == null ? null : kde_accent_in (kde);
            }
            return gnome_accent_from_settings ();
        }

        private static bool desktop_prefers_dark () {
            var desktop = Desktop.get_default ().primary;

            if (is_kde (desktop)) {
                var kde = read_kdeglobals ();
                return kde != null && kde_prefers_dark_in (kde);
            }

            // Read beyond GNOME too: the setting is the closest thing Linux has
            // to a portable "I want dark", and a sway user who set it means it.
            var interface_settings = settings_if_key_exists ("org.gnome.desktop.interface", "color-scheme");
            if (interface_settings != null)
                return interface_settings.get_string ("color-scheme") == "prefer-dark";

            return false;
        }

        private static bool is_kde (string desktop) {
            return desktop == "kde" || desktop == "plasma";
        }

        private static string? read_kdeglobals () {
            var file = Path.build_filename (Environment.get_user_config_dir (), "kdeglobals");
            string contents;
            try {
                if (!FileUtils.get_contents (file, out contents)) return null;
            } catch (Error e) {
                return null;
            }
            return contents;
        }

        /**
         * GNOME 47 and later. Older GNOME has no such key, and constructing a
         * Settings for a key a schema does not have aborts the process rather
         * than returning an error — the same trap GnomeResolver documents.
         */
        private static string? gnome_accent_from_settings () {
            var settings = settings_if_key_exists ("org.gnome.desktop.interface", "accent-color");
            if (settings == null) return null;
            return gnome_accent_hex (settings.get_string ("accent-color"));
        }

        private static GLib.Settings? settings_if_key_exists (string schema_id, string key) {
            var source = GLib.SettingsSchemaSource.get_default ();
            if (source == null) return null;
            var schema = source.lookup (schema_id, true);
            if (schema == null || !schema.has_key (key)) return null;
            return new GLib.Settings.full (schema, null, null);
        }

        // ---- pure parsing, held to account by tests/test_palette ----

        /**
         * KDE writes `AccentColor=61,174,233` — decimal RGB, not hex.
         *
         * Parsed by hand rather than with KeyFile because kdeglobals is a large
         * file with groups this app has no business loading, and one line is all
         * that is wanted.
         */
        internal static string? kde_accent_in (string kdeglobals) {
            var value = ini_value_in (kdeglobals, "AccentColor");
            if (value == null) return null;

            var parts = value.split (",");
            if (parts.length != 3) return null;

            int[] channels = {};
            foreach (var part in parts) {
                var text = part.strip ();
                if (text.length == 0) return null;
                foreach (var c in text.to_utf8 ()) {
                    if (!c.isdigit ()) return null;
                }
                var n = int.parse (text);
                if (n < 0 || n > 255) return null;
                channels += n;
            }
            return "#%02x%02x%02x".printf (channels[0], channels[1], channels[2]);
        }

        /** KDE names a dark scheme rather than flagging it. */
        internal static bool kde_prefers_dark_in (string kdeglobals) {
            var scheme = ini_value_in (kdeglobals, "ColorScheme");
            return scheme != null && scheme.down ().contains ("dark");
        }

        private static string? ini_value_in (string contents, string key) {
            foreach (var line in contents.split ("\n")) {
                var trimmed = line.strip ();
                if (!trimmed.has_prefix (key)) continue;
                var eq = trimmed.index_of ("=");
                if (eq < 0) continue;
                if (trimmed.slice (0, eq).strip () != key) continue;
                return trimmed.slice (eq + 1, trimmed.length).strip ();
            }
            return null;
        }

        /** Adwaita's palette, behind the names GNOME stores. */
        internal static string? gnome_accent_hex (string name) {
            switch (name.down ()) {
                case "blue":   return "#3584e4";
                case "teal":   return "#2190a4";
                case "green":  return "#3a944a";
                case "yellow": return "#c88800";
                case "orange": return "#ed5b00";
                case "red":    return "#e62d42";
                case "pink":   return "#d56199";
                case "purple": return "#9141ac";
                case "slate":  return "#6f8396";
                default:       return null;
            }
        }

        /**
         * The shipped accent for a desktop that will not say.
         *
         * Each is that desktop's own house colour, which is the point of the
         * exercise: the same branding should feel like it belongs on whichever
         * desktop it is running on.
         */
        internal static string default_accent_for (string desktop) {
            switch (desktop) {
                case "regolith":
                case "sway":
                case "i3":       return "#2f6fb5";   // matches the shipped theme.css
                case "gnome":    return "#3584e4";   // Adwaita blue
                case "kde":
                case "plasma":   return "#3daee9";   // Breeze blue
                case "hyprland": return "#33ccff";
                default:         return DEFAULT_ACCENT;
            }
        }

        /**
         * `#rrggbb`, and nothing else.
         *
         * Strict because this string is interpolated into a stylesheet: a value
         * out of branding.conf that carried a `;` or a `}` would be a distro
         * writing arbitrary CSS through a colour key, and a colour is not a
         * place where that should be possible.
         */
        internal static bool is_hex_colour (string value) {
            if (value.length != 7 || !value.has_prefix ("#")) return false;
            for (int i = 1; i < value.length; i++) {
                if (!value[i].isxdigit ()) return false;
            }
            return true;
        }
    }
}
